In [11]:
import pandas as pd
import numpy as np
from fuzzywuzzy import fuzz

In [ ]:
pip install python-Levenshtein

Collecting python-Levenshtein
  Downloading python_Levenshtein-0.26.0-py3-none-any.whl.metadata (3.7 kB)
Collecting Levenshtein==0.26.0 (from python-Levenshtein)
  Downloading levenshtein-0.26.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting rapidfuzz<4.0.0,>=3.9.0 (from Levenshtein==0.26.0->python-Levenshtein)
  Downloading rapidfuzz-3.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Downloading python_Levenshtein-0.26.0-py3-none-any.whl (9.4 kB)
Downloading levenshtein-0.26.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 9.8 MB/s eta 0:00:00
Downloading rapidfuzz-3.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 53.5 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, Levenshtein, python-Levenshtein
Successfully installed Levenshtein-0.26.0 python-Levenshtein-0.26.0 rapidfuzz-3.10.0

In [ ]:
Str1 = "Mcdonald Resto, Alam Sutera"
Str2 = "Mcd, Alam Sutera"
Ratio = fuzz.ratio(Str1.lower(),Str2.lower())
Partial_Ratio = fuzz.partial_ratio(Str1.lower(),Str2.lower())
Token_Sort_Ratio = fuzz.token_sort_ratio(Str1,Str2)
Token_Set_Ratio = fuzz.token_set_ratio(Str1,Str2)
print(Ratio)
print(Partial_Ratio)
print(Token_Sort_Ratio)
print(Token_Set_Ratio)

74
81
73
85

In [ ]:
Str1 = "sitting"
Str2 = "kitten"
Ratio = fuzz.ratio(Str1.lower(),Str2.lower())
Partial_Ratio = fuzz.partial_ratio(Str1.lower(),Str2.lower())
Token_Sort_Ratio = fuzz.token_sort_ratio(Str1,Str2)
Token_Set_Ratio = fuzz.token_set_ratio(Str1,Str2)
print(Ratio)
print(Partial_Ratio)
print(Token_Sort_Ratio)
print(Token_Set_Ratio)

62
67
62
62

In [ ]:
df = pd.read_excel('merchant_checking.xlsx')
df.head(10)

,merchant_id_shp,merchant_name_shp,gps_latitude_shp,gps_longitude_shp,outlet_id_shp,outlet_name_shp,merchant_id_comp,merchant_name_comp,latitude_comp,longitude_comp
0,8212,Bakso Jawir (JWR),-6.15072,106.70270,8221,"JWR Ruko, Duta Indah",542538094,"Bakso Jawir (JWR), Ruko Duta Indah",-6.147444,106.702417
1,8845,PRIMA FRESHMART 1,-6.14760,106.70244,9114,"PFM, KALIDERES JXDRES1",543399556,"Prima Freshmart, Kalideres",-6.147619,106.702415
2,478827,Domino's Pizza_,-6.14420,106.70634,479580,"Domino's, Pizza Citra 3",542531234,"Domino's Pizza, Citra Garden 2",-6.144993,106.706230
3,15754,KFC,-6.15605,106.71623,17215,"KFC, DAAN MOGOT BARU",542675827,"KFC, Daan Mogot Baru",-6.153440,106.713879
4,40549,MCDONALDS,-6.15092,106.71446,82467,"McD, Mal Daan Mogot FC",542530624,"McDonald's, Mal Daan Mogot",-6.151077,106.714432
5,5284,Kopi Soe,-6.14682,106.70845,5288,"Kopi Soe, GoWork CP",543119305,"Kopi Kenangan, GoWork CP",-6.148143,106.708149
6,32120,CHATIME,-6.15179,106.71361,115076,"CHATIME, MATAHARI DAAN MGT",543283041,"Chatime, Mall Matahari Daan Mogot",-6.151232,106.714229
7,118743,Alfamart,-7.99146,112.68444,159902,"ALFAMART, NGANTANG MALANG",543342911,"Halal Mart HNI, Kedungkandang",-7.987778,112.676896
8,36096,Mie Dua Rasa,-7.73868,109.00742,36434,Mie Dua Rasa,542630974,Mie 2 Rasa,-7.737617,109.007828
9,124512,Ayam Rasa Bu Darmi,-7.95146,112.65444,67890,"ARBD, Surabaya",543642912,Bu Darmi Ayam Rasa,-7.951460,112.654440

In [10]:
df.info()

NameError: name 'df' is not defined

In [ ]:
#applying fuzzy wuzzy to dataframe

#changing data frame to list
outlet_name_shp = df.outlet_name_shp.values.tolist()
merchant_name_comp = df.merchant_name_comp.values.tolist()

#using 2 ratio to compare full part name with partial part
ratio = []
partial_ratio = []
token_sort_ratio = []
token_set_ratio = []

for i in range(0,len(outlet_name_shp)):
    r1 = fuzz.ratio(outlet_name_shp[i].lower(), merchant_name_comp[i].lower())
    r2 = fuzz.partial_ratio(outlet_name_shp[i].lower(), merchant_name_comp[i].lower())
    r3 = fuzz.token_sort_ratio(outlet_name_shp[i], merchant_name_comp[i])
    r4 = fuzz.token_set_ratio(outlet_name_shp[i], merchant_name_comp[i])
    ratio.append(r1)
    partial_ratio.append(r2)
    token_sort_ratio.append(r3)
    token_set_ratio.append(r4)

In [ ]:
df['ratio'] = pd.Series(ratio)
df['partial_ratio'] = pd.Series(partial_ratio)
df['token_sort_ratio'] = pd.Series(token_sort_ratio)
df['token_set_ratio'] = pd.Series(token_set_ratio)

In [ ]:
df.head(10)

,merchant_id_shp,merchant_name_shp,gps_latitude_shp,gps_longitude_shp,outlet_id_shp,outlet_name_shp,merchant_id_comp,merchant_name_comp,latitude_comp,longitude_comp,ratio,partial_ratio,token_sort_ratio,token_set_ratio
0,8212,Bakso Jawir (JWR),-6.15072,106.70270,8221,"JWR Ruko, Duta Indah",542538094,"Bakso Jawir (JWR), Ruko Duta Indah",-6.147444,106.702417,70,90,76,100
1,8845,PRIMA FRESHMART 1,-6.14760,106.70244,9114,"PFM, KALIDERES JXDRES1",543399556,"Prima Freshmart, Kalideres",-6.147619,106.702415,58,60,70,70
2,478827,Domino's Pizza_,-6.14420,106.70634,479580,"Domino's, Pizza Citra 3",542531234,"Domino's Pizza, Citra Garden 2",-6.144993,106.706230,79,91,82,95
3,15754,KFC,-6.15605,106.71623,17215,"KFC, DAAN MOGOT BARU",542675827,"KFC, Daan Mogot Baru",-6.153440,106.713879,100,100,100,100
4,40549,MCDONALDS,-6.15092,106.71446,82467,"McD, Mal Daan Mogot FC",542530624,"McDonald's, Mal Daan Mogot",-6.151077,106.714432,78,81,78,80
5,5284,Kopi Soe,-6.14682,106.70845,5288,"Kopi Soe, GoWork CP",543119305,"Kopi Kenangan, GoWork CP",-6.148143,106.708149,79,68,68,88
6,32120,CHATIME,-6.15179,106.71361,115076,"CHATIME, MATAHARI DAAN MGT",543283041,"Chatime, Mall Matahari Daan Mogot",-6.151232,106.714229,88,81,88,91
7,118743,Alfamart,-7.99146,112.68444,159902,"ALFAMART, NGANTANG MALANG",543342911,"Halal Mart HNI, Kedungkandang",-7.987778,112.676896,59,56,50,50
8,36096,Mie Dua Rasa,-7.73868,109.00742,36434,Mie Dua Rasa,542630974,Mie 2 Rasa,-7.737617,109.007828,82,70,82,89
9,124512,Ayam Rasa Bu Darmi,-7.95146,112.65444,67890,"ARBD, Surabaya",543642912,Bu Darmi Ayam Rasa,-7.951460,112.654440,38,43,45,45

In [ ]:
df[df['token_sort_ratio'] >= 70].to_excel('result.xlsx')

PermissionError: [Errno 13] Permission denied: 'result.xlsx'

In [ ]:
pip install fugue[all]

Collecting fugue[all]
  Using cached fugue-0.8.2-py3-none-any.whl (370 kB)
Collecting adagio>=0.2.4
  Using cached adagio-0.2.4-py3-none-any.whl (26 kB)
Processing c:\users\anugrah.rusdianto\appdata\local\pip\cache\wheels\3f\d7\6c\cd3e084a96b2d80df8c85d36fb3e2b2013595a0e5109515388\fugue_sql_antlr-0.1.6-py3-none-any.whl
Collecting triad>=0.8.4
  Using cached triad-0.8.4-py3-none-any.whl (76 kB)
Collecting pyarrow>=0.15.1
  Using cached pyarrow-11.0.0-cp38-cp38-win_amd64.whl (20.6 MB)
Requirement already satisfied: jinja2 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from fugue[all]) (2.11.2)
Collecting sqlglot
  Using cached sqlglot-11.4.5-py3-none-any.whl (242 kB)
Collecting pandas<2,>=1.2.0
  Using cached pandas-1.5.3-cp38-cp38-win_amd64.whl (11.0 MB)
Collecting qpd>=0.4.0
  Using cached qpd-0.4.0-py3-none-any.whl (187 kB)
Requirement already satisfied: notebook; extra == "all" in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from fugue[all]) (6.1.4)
Collecting ibis-framework>=3.2.0; python_version >= "3.8" and extra == "all"
  Using cached ibis_framework-5.0.0-py3-none-any.whl (1.3 MB)
Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: jupyterlab; extra == "all" in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from fugue[all]) (2.2.6)
Collecting dask[dataframe,distributed]>=2022.9.0; python_version >= "3.8" and extra == "all"
  Using cached dask-2023.3.2-py3-none-any.whl (1.2 MB)
Collecting ray[data]>=2.0.0; extra == "all"
  Using cached ray-2.3.1-cp38-cp38-win_amd64.whl (21.7 MB)
Collecting duckdb>=0.5.0; extra == "all"
  Using cached duckdb-0.7.1-cp38-cp38-win_amd64.whl (9.5 MB)
Collecting pyspark; extra == "all"
  Downloading pyspark-3.3.2.tar.gz (281.4 MB)
Requirement already satisfied: ipython>=7.10.0; extra == "all" in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from fugue[all]) (7.19.0)
Collecting polars; extra == "all"
  Using cached polars-0.16.16-cp37-abi3-win_amd64.whl (17.6 MB)
Collecting antlr4-python3-runtime<4.12,>=4.11.1
  Using cached antlr4_python3_runtime-4.11.1-py3-none-any.whl (144 kB)
Collecting fs
  Using cached fs-2.4.16-py2.py3-none-any.whl (135 kB)
Requirement already satisfied: six in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from triad>=0.8.4->fugue[all]) (1.15.0)
Requirement already satisfied: numpy in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from triad>=0.8.4->fugue[all]) (1.24.1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from jinja2->fugue[all]) (1.1.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from pandas<2,>=1.2.0->fugue[all]) (2020.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from pandas<2,>=1.2.0->fugue[all]) (2.8.1)
Requirement already satisfied: Send2Trash in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook; extra == "all"->fugue[all]) (1.5.0)
Requirement already satisfied: prometheus-client in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook; extra == "all"->fugue[all]) (0.8.0)
Requirement already satisfied: traitlets>=4.2.1 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook; extra == "all"->fugue[all]) (5.0.5)
Requirement already satisfied: ipython-genutils in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook; extra == "all"->fugue[all]) (0.2.0)
Requirement already satisfied: jupyter-core>=4.6.1 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook; extra == "all"->fugue[all]) (4.6.3)
Requirement already satisfied: ipykernel in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook; extra == "all"->fugue[all]) (5.3.4)
Requirement already satisfied: nbformat in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook; extra == "all"->fugue[all]) (5.0.8)
Requirement already satisfied: terminado>=0.8.3 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook; extra == "all"->fugue[all]) (0.9.1)
Requirement already satisfied: pyzmq>=17 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook; extra == "all"->fugue[all]) (19.0.2)
Requirement already satisfied: tornado>=5.0 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook; extra == "all"->fugue[all]) (6.0.4)

WARNING: No metadata found in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'c:\\users\\anugrah.rusdianto\\anaconda3\\lib\\site-packages\\tornado-6.0.4.dist-info\\METADATA'

In [ ]:
pip install fugue-jupyter

Collecting fugue-jupyter
  Using cached fugue_jupyter-0.2.2-py3-none-any.whl (95 kB)
Collecting fugue>=0.8.0
  Using cached fugue-0.8.2-py3-none-any.whl (370 kB)
Requirement already satisfied: notebook in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from fugue-jupyter) (6.1.4)
Collecting jupyterlab-lsp
  Using cached jupyterlab_lsp-4.0.1-py3-none-any.whl (1.8 MB)
Requirement already satisfied: ipython>=7.10.0 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from fugue-jupyter) (7.19.0)
Collecting jupyterlab>=3.0
  Using cached jupyterlab-3.6.2-py3-none-any.whl (8.9 MB)
Collecting sqlglot
  Using cached sqlglot-11.4.5-py3-none-any.whl (242 kB)
Collecting adagio>=0.2.4
  Using cached adagio-0.2.4-py3-none-any.whl (26 kB)
Collecting pyarrow>=0.15.1
  Using cached pyarrow-11.0.0-cp38-cp38-win_amd64.whl (20.6 MB)
Collecting triad>=0.8.4
  Using cached triad-0.8.4-py3-none-any.whl (76 kB)
Collecting qpd>=0.4.0
  Using cached qpd-0.4.0-py3-none-any.whl (187 kB)
Processing c:\users\anugrah.rusdianto\appdata\local\pip\cache\wheels\3f\d7\6c\cd3e084a96b2d80df8c85d36fb3e2b2013595a0e5109515388\fugue_sql_antlr-0.1.6-py3-none-any.whl
Requirement already satisfied: pandas<2,>=1.2.0 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from fugue>=0.8.0->fugue-jupyter) (1.5.3)
Requirement already satisfied: jinja2 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from fugue>=0.8.0->fugue-jupyter) (2.11.2)
Requirement already satisfied: tornado>=5.0 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (6.2)
Requirement already satisfied: nbconvert in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (6.0.7)
Requirement already satisfied: ipykernel in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (5.3.4)
Requirement already satisfied: traitlets>=4.2.1 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (5.0.5)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (6.1.7)
Requirement already satisfied: pyzmq>=17 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (19.0.2)
Requirement already satisfied: nbformat in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (5.0.8)
Requirement already satisfied: jupyter-core>=4.6.1 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (4.6.3)
Requirement already satisfied: argon2-cffi in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (20.1.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (0.9.1)
Requirement already satisfied: prometheus-client in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (0.8.0)
Requirement already satisfied: ipython-genutils in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (0.2.0)
Requirement already satisfied: Send2Trash in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from notebook->fugue-jupyter) (1.5.0)
Collecting jupyter-lsp>=2.0.0
  Using cached jupyter_lsp-2.0.1-py3-none-any.whl (63 kB)
Requirement already satisfied: decorator in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from ipython>=7.10.0->fugue-jupyter) (4.4.2)
Requirement already satisfied: pygments in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from ipython>=7.10.0->fugue-jupyter) (2.7.2)
Requirement already satisfied: backcall in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from ipython>=7.10.0->fugue-jupyter) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from ipython>=7.10.0->fugue-jupyter) (3.0.8)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from ipython>=7.10.0->fugue-jupyter) (0.4.4)
Requirement already satisfied: pickleshare in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from ipython>=7.10.0->fugue-jupyter) (0.7.5)
Requirement already satisfied: setuptools>=18.5 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from ipython>=7.10.0->fugue-jupyter) (50.3.1.post20201107)
Requirement already satisfied: jedi>=0.10 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from ipython>=7.10.0->fugue-jupyter) (0.17.1)
Collecting jupyter-server<3,>=1.16.0
  Using cached jupyter_server-2.5.0-py3-none-any.whl (366 kB)
Collecting tomli; python_version < "3.11"
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Requirement already satisfied: packaging in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from jupyterlab>=3.0->fugue-jupyter) (20.4)
Collecting jupyterlab-server~=2.19
  Using cached jupyterlab_server-2.21.0-py3-none-any.whl (56 kB)
Collecting nbclassic
  Using cached nbclassic-0.5.4-py3-none-any.whl (10.0 MB)
Collecting jupyter-ydoc~=0.2.3
  Using cached jupyter_ydoc-0.2.3-py3-none-any.whl (5.9 kB)
Collecting jupyter-server-ydoc~=0.8.0
  Using cached jupyter_server_ydoc-0.8.0-py3-none-any.whl (11 kB)
Requirement already satisfied: numpy>=1.16.6 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from pyarrow>=0.15.1->fugue>=0.8.0->fugue-jupyter) (1.24.1)
Requirement already satisfied: six in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from triad>=0.8.4->fugue>=0.8.0->fugue-jupyter) (1.15.0)
Collecting fs
  Using cached fs-2.4.16-py2.py3-none-any.whl (135 kB)
Collecting antlr4-python3-runtime<4.12,>=4.11.1
  Using cached antlr4_python3_runtime-4.11.1-py3-none-any.whl (144 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from pandas<2,>=1.2.0->fugue>=0.8.0->fugue-jupyter) (2.8.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from pandas<2,>=1.2.0->fugue>=0.8.0->fugue-jupyter) (2020.1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from jinja2->fugue>=0.8.0->fugue-jupyter) (1.1.1)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from nbconvert->notebook->fugue-jupyter) (0.8.4)
Requirement already satisfied: testpath in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from nbconvert->notebook->fugue-jupyter) (0.4.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from nbconvert->notebook->fugue-jupyter) (0.5.1)
Requirement already satisfied: defusedxml in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from nbconvert->notebook->fugue-jupyter) (0.6.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from nbconvert->notebook->fugue-jupyter) (1.4.3)
Requirement already satisfied: jupyterlab-pygments in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from nbconvert->notebook->fugue-jupyter) (0.1.2)
Requirement already satisfied: bleach in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from nbconvert->notebook->fugue-jupyter) (3.2.1)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from nbconvert->notebook->fugue-jupyter) (0.3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from nbformat->notebook->fugue-jupyter) (3.2.0)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from jupyter-core>=4.6.1->notebook->fugue-jupyter) (227)
Requirement already satisfied: cffi>=1.0.0 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from argon2-cffi->notebook->fugue-jupyter) (1.14.3)
Requirement already satisfied: pywinpty>=0.5 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook->fugue-jupyter) (0.5.7)
Requirement already satisfied: importlib-metadata>=4.8.3; python_version < "3.10" in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from jupyter-lsp>=2.0.0->jupyterlab-lsp->fugue-jupyter) (6.1.0)
Requirement already satisfied: wcwidth in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.10.0->fugue-jupyter) (0.2.5)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from jedi>=0.10->ipython>=7.10.0->fugue-jupyter) (0.7.0)
Collecting anyio>=3.1.0
  Using cached anyio-3.6.2-py3-none-any.whl (80 kB)
Requirement already satisfied: jupyter-server-terminals in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from jupyter-server<3,>=1.16.0->jupyterlab>=3.0->fugue-jupyter) (0.4.4)
Collecting websocket-client
  Using cached websocket_client-1.5.1-py3-none-any.whl (55 kB)
Collecting jupyter-events>=0.4.0
  Using cached jupyter_events-0.6.3-py3-none-any.whl (18 kB)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from packaging->jupyterlab>=3.0->fugue-jupyter) (2.4.7)
Collecting babel>=2.10
  Using cached Babel-2.12.1-py3-none-any.whl (10.1 MB)
Requirement already satisfied: json5>=0.9.0 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from jupyterlab-server~=2.19->jupyterlab>=3.0->fugue-jupyter) (0.9.5)
Collecting requests>=2.28
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting notebook-shim>=0.1.0
  Using cached notebook_shim-0.2.2-py3-none-any.whl (13 kB)
Collecting nest-asyncio>=1.5
  Using cached nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
Collecting y-py<0.6.0,>=0.5.3
  Using cached y_py-0.5.9-cp38-none-win_amd64.whl (554 kB)
Collecting ypy-websocket<0.9.0,>=0.8.2
  Using cached ypy_websocket-0.8.4-py3-none-any.whl (10 kB)
Collecting jupyter-server-fileid<1,>=0.6.0
  Using cached jupyter_server_fileid-0.8.0-py3-none-any.whl (15 kB)
Collecting appdirs~=1.4.3
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: async-generator in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook->fugue-jupyter) (1.10)
Requirement already satisfied: webencodings in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from bleach->nbconvert->notebook->fugue-jupyter) (0.5.1)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->fugue-jupyter) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->fugue-jupyter) (20.3.0)
Requirement already satisfied: pycparser in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook->fugue-jupyter) (2.20)
Requirement already satisfied: zipp>=0.5 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from importlib-metadata>=4.8.3; python_version < "3.10"->jupyter-lsp>=2.0.0->jupyterlab-lsp->fugue-jupyter) (3.4.0)
Requirement already satisfied: idna>=2.8 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=1.16.0->jupyterlab>=3.0->fugue-jupyter) (2.10)
Collecting sniffio>=1.1
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting rfc3986-validator>=0.1.1
  Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl (4.2 kB)
Collecting python-json-logger>=2.0.4
  Using cached python_json_logger-2.0.7-py3-none-any.whl (8.1 kB)
Collecting rfc3339-validator
  Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl (3.5 kB)
Requirement already satisfied: pyyaml>=5.3 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from jupyter-events>=0.4.0->jupyter-server<3,>=1.16.0->jupyterlab>=3.0->fugue-jupyter) (5.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from requests>=2.28->jupyterlab-server~=2.19->jupyterlab>=3.0->fugue-jupyter) (1.25.11)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp38-cp38-win_amd64.whl (96 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from requests>=2.28->jupyterlab-server~=2.19->jupyterlab>=3.0->fugue-jupyter) (2020.6.20)
Collecting aiosqlite<1,>=0.17.0
  Using cached aiosqlite-0.18.0-py3-none-any.whl (15 kB)
Collecting aiofiles<23,>=22.1.0
  Using cached aiofiles-22.1.0-py3-none-any.whl (14 kB)
Installing collected packages: sqlglot, pyarrow, appdirs, fs, triad, adagio, antlr4-python3-runtime, qpd, fugue-sql-antlr, fugue, sniffio, anyio, websocket-client, rfc3986-validator, python-json-logger, rfc3339-validator, jupyter-events, jupyter-server, tomli, babel, charset-normalizer, requests, jupyterlab-server, notebook-shim, nest-asyncio, nbclassic, y-py, jupyter-ydoc, aiosqlite, aiofiles, ypy-websocket, jupyter-server-fileid, jupyter-server-ydoc, jupyterlab, jupyter-lsp, jupyterlab-lsp, fugue-jupyter
  Attempting uninstall: babel
    Found existing installation: Babel 2.8.1
    Uninstalling Babel-2.8.1:
      Successfully uninstalled Babel-2.8.1
  Attempting uninstall: requests
    Found existing installation: requests 2.24.0
    Uninstalling requests-2.24.0:
      Successfully uninstalled requests-2.24.0
  Attempting uninstall: jupyterlab-server
    Found existing installation: jupyterlab-server 1.2.0
    Uninstalling jupyterlab-server-1.2.0:
      Successfully uninstalled jupyterlab-server-1.2.0
  Attempting uninstall: nest-asyncio
    Found existing installation: nest-asyncio 1.4.2
    Uninstalling nest-asyncio-1.4.2:
      Successfully uninstalled nest-asyncio-1.4.2
  Attempting uninstall: jupyterlab
    Found existing installation: jupyterlab 2.2.6
    Uninstalling jupyterlab-2.2.6:
      Successfully uninstalled jupyterlab-2.2.6
Successfully installed adagio-0.2.4 aiofiles-22.1.0 aiosqlite-0.18.0 antlr4-python3-runtime-4.11.1 anyio-3.6.2 appdirs-1.4.4 babel-2.12.1 charset-normalizer-3.1.0 fs-2.4.16 fugue-0.8.2 fugue-jupyter-0.2.2 fugue-sql-antlr-0.1.6 jupyter-events-0.6.3 jupyter-lsp-2.0.1 jupyter-server-2.5.0 jupyter-server-fileid-0.8.0 jupyter-server-ydoc-0.8.0 jupyter-ydoc-0.2.3 jupyterlab-3.6.2 jupyterlab-lsp-4.0.1 jupyterlab-server-2.21.0 nbclassic-0.5.4 nest-asyncio-1.5.6 notebook-shim-0.2.2 pyarrow-11.0.0 python-json-logger-2.0.7 qpd-0.4.0 requests-2.28.2 rfc3339-validator-0.1.4 rfc3986-validator-0.1.1 sniffio-1.3.0 sqlglot-11.4.5 tomli-2.0.1 triad-0.8.4 websocket-client-1.5.1 y-py-0.5.9 ypy-websocket-0.8.4
Note: you may need to restart the kernel to use updated packages.

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

jupyterlab-server 2.21.0 requires jinja2>=3.0.3, but you'll have jinja2 2.11.2 which is incompatible.
jupyterlab-server 2.21.0 requires jsonschema>=4.17.3, but you'll have jsonschema 3.2.0 which is incompatible.
jupyterlab-server 2.21.0 requires packaging>=21.3, but you'll have packaging 20.4 which is incompatible.
jupyter-events 0.6.3 requires traitlets>=5.3, but you'll have traitlets 5.0.5 which is incompatible.
jupyter-server 2.5.0 requires jupyter-client>=7.4.4, but you'll have jupyter-client 6.1.7 which is incompatible.
jupyter-server 2.5.0 requires jupyter-core!=5.0.*,>=4.12, but you'll have jupyter-core 4.6.3 which is incompatible.
jupyter-server 2.5.0 requires nbconvert>=6.4.4, but you'll have nbconvert 6.0.7 which is incompatible.
jupyter-server 2.5.0 requires nbformat>=5.3.0, but you'll have nbformat 5.0.8 which is incompatible.
jupyter-server 2.5.0 requires pyzmq>=24, but you'll have pyzmq 19.0.2 which is incompatible.
jupyter-server 2.5.0 requires traitlets>=5.6.0, but you'll have traitlets 5.0.5 which is incompatible.
nbclassic 0.5.4 requires Send2Trash>=1.8.0, but you'll have send2trash 1.5.0 which is incompatible.
ypy-websocket 0.8.4 requires y-py<0.7.0,>=0.6.0, but you'll have y-py 0.5.9 which is incompatible.